---
language: node_js
node_js:
  - 4
  - stable
dist: precise
cache:
  yarn: true
  directories:
  - node_modules
env:
  - NODE_ENV=development
  - NODE_ENV=production
matrix:
  allow_failures:
    - env: NODE_ENV=production
  fast_finish: true
install:
  - yarn --production=false
before_script:
  - if [ "${NODE_ENV}" = "production" ]; then yarn build; fi
script:
  - yarn lint
  - AST_COMPARE=1 yarn test -- --runInBand
  - if [ "${NODE_ENV}" = "development" ]; then yarn codecov; fi
deploy:
  provider: script
  script: website/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    node: stable
